In [1]:
import numpy as np

In [2]:
def d_0(A):
    return (1./8)*(6*A[0][1]+A[0][0]+A[0][2]+4*A[1][0]+4*A[1][2]+3*(2*A[1][1]-A[1][0]-A[1][2])*(A[0][3]/A[1][3]))

In [3]:
c11=[(0.5, 1, 1.5, 0.6), (0.25, 1, 1.75, 0.9)]
a1=[(6, 7, 12, 0.6), (5,7,15, 0.9)]

In [4]:
np.array(c11).shape

(2, 4)

In [5]:
0.5*d_0(a1)

8.0

In [6]:
np.empty(2)

array([-5.73021895e-300,  4.66665801e-310])

In [89]:
def Lagrangian(x, lambda_, nu):
    return np.sum([np.sum([np.sum([c[k][i][j] for j in range(c.shape[2])])\
        for i in range(c.shape[1])])**2 for k in range(c.shape[0])])+np.sum([np.sum([lambda_[i][j]*x[i][j]\
        for j in range(x.shape[1])]) for i in range(x.shape[0])])+np.sum([nu[j]*(np.sum([x[i][j]\
        for i in range(x.shape[0])])-b[j]) for j in range(x.shape[1])])+np.sum([nu[x.shape[1]+i]*(np.sum([x[i][j]\
        for j in range(x.shape[1])])-a[i]) for i in range(x.shape[0])])

In [81]:
def grad_x(x, lambda_, nu):
    L=np.empty((x.shape[0], x.shape[1]))
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            L[i][j]=2.0*np.sum([c[k][i][j]*np.sum([np.sum([c[k][l][s]*x[l][s] for s in range(c.shape[2])])\
                            for l in range(c.shape[1])]) for k in range(c.shape[0])])-lambda_[i][j]+nu[j]\
            +nu[x.shape[1]+i]
    return L

In [82]:
def grad_lambda(x):
    return x

In [83]:
def grad_nu(x):
    v=np.empty(x.shape[1]+x.shape[0])
    for l in range(len(v)):
        if l<x.shape[1]:
            v[l]=np.sum([x[i][l] for i in range(x.shape[0])])-b[l]
        else:
            v[l]=np.sum([x[l-x.shape[1]][j] for j in range(x.shape[1])])-a[l-x.shape[1]]
    return v

In [84]:
c=np.array([[[2.,4,14,14], [2,18,6,8],[16,18,8,12]], [[8.,8,6,6], [10,16,18,20],[12,4,10,2]]])
a=np.array([8.,19,17])
b=np.array([11.,3,14,16])

In [85]:
x[(x<0)]

array([-2.98176834, -0.37120674, -1.43617475, -1.49850387])

In [86]:
x

array([[ 2.91726083,  2.79334563,  1.21215183,  1.20356671],
       [ 2.63057786, -2.98176834, -0.37120674, -1.43617475],
       [-1.49850387,  0.32504321,  0.97215883,  1.79669888]])

In [87]:
5+np.random.randn(3,4)

array([[5.20412304, 5.56341312, 4.44319452, 5.13659937],
       [4.9379797 , 6.13200995, 4.72936676, 5.1051457 ],
       [3.80696927, 3.77002987, 4.11751852, 4.00885097]])

In [165]:
(x<5).any()

True

In [234]:
# x=np.full((c.shape[1], c.shape[2]), 10.0)
# lambda_=np.full((c.shape[1], c.shape[2]), 1.0)
# nu=np.ones(c.shape[1]+c.shape[2])
# lr=0.00005
# Num_iter=100

# for i in range(Num_iter):
#     nu[grad_nu(x) != 0.0]=0.0
# #     print(x)
# #     print()
#     x -= lr*grad_x(x, lambda_, nu)
# #     if (x<0.0).any():
# #         x[x<0.0] += 10.
#     lambda_ -= lr*grad_lambda(x)
#     nu -= lr*grad_nu(x)
#     if i%10==0:
#         print("epoch:", i)
#         print()
#         print("grad_x:", grad_x(x, lambda_, nu))
#         print()
#         print("grad_nu:", grad_nu(x))
#         print()
#         print("grad_lambda:", grad_lambda(x))
#         print("loss:", Lagrangian(x, lambda_, nu))
#         print()

In [194]:
P=np.array([[[3/4,1/4], [1/3,2/3], [5/6,1/6]], [[2/5, 3/5],[4/5,1/5], [8/10,2/10]]])
Pi=np.array([[1,2,3], [6,4,5]])

# Wrapper methods with Kfold cross validation

In [1]:
import pandas as pd
import LogisticRegression as LR
import numpy as np

In [2]:
from sklearn import datasets

In [3]:
data = datasets.load_wine()

In [4]:
Data = pd.concat([pd.DataFrame(data.data, columns = data.feature_names), pd.Series(data.target, name = 'target')], axis=1)

In [30]:
Data

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [6]:
class Kfold:
    def __init__(self, K=5):
        self.K = K
    def split(self, data):
        Random = list(range(len(data)))
        np.random.shuffle(Random)
        data = data.iloc[Random]
        Folds = []
        n = len(data)
        for i in range(self.K):
            Folds.append(data.iloc[i*(n//self.K) : (i+1)*(n//self.K)])
        return Folds
    def evaluate_model(self, model, data):
        Folds = self.split(data)
        Error = []
        for i in range(self.K):
            Test_data = Folds[i]
            Train_data = pd.DataFrame([], columns = Test_data.columns)
            for j in range(self.K):
                if j != i:
                    Train_data = pd.concat([Train_data, Folds[j]])
            model.fit(Train_data.iloc[:,:-1], Train_data.iloc[:,-1])
            Error.append((model.predict(Test_data.iloc[:,:-1].values)==Test_data.iloc[:,-1].values).mean())
        return Error

In [56]:
model = LR.MulticlassLogReg(lr=0.08, Max_iter=200)
KFold = Kfold()

In [57]:
model.fit(Data.iloc[:,:-1], Data.iloc[:,-1])

In [58]:
model.predict(Data.iloc[:,:-1].values)

array([0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2,
       0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 1, 1, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [59]:
(model.predict(Data.iloc[:,:-1].values)==Data.iloc[:,-1].values).mean()

0.601123595505618

In [10]:
KFold.evaluate_model(model=model, data=Data)

[0.45714285714285713,
 0.5428571428571428,
 0.3142857142857143,
 0.22857142857142856,
 0.22857142857142856]